Feature/swagger/training
DariaBoreysha/swagger_petstore_autotest pull request #1
Opened 2024-05-08 14:04 UTC by DariaBoreysha

2024-05-08 14:48 UTC, Diinal requested changes
Хороший страт

2024-05-08 14:48 UTC, Diinal commented on build.gradle
> +task cucumber() {
не хватает параметра для тегов, чтобы можно было отдельные сценарии запускать.

2024-05-08 14:48 UTC, Diinal commented on src/test/resources/features/SWAGGER(FindByStatus).feature
> +    When формируем GET запрос с валидным параметром "status" со значением "<status>", отправляем на "https://petstore.swagger.io/v2/pet/findByStatus" и сохраняем ответ как "response_body"
куда сохраняем ответ?
что значит валидный параметр?

2024-05-08 14:48 UTC, Diinal commented on src/test/resources/features/SWAGGER(FindByStatus).feature
> +      | header | value            |
хэдеры будут разными в сценариях? Точно нужно?

2024-05-08 14:48 UTC, Diinal commented on src/test/java/client/HttpClient.java
> +        assertAnswerStatusIsOk(response
тут это лишнее, у тебя же отдельный шаг есть для проверки статус кода
он не всегда будет 200 ОК, негативные сценарии тоже нужны

2024-05-08 14:48 UTC, Diinal commented on src/test/java/client/HttpClient.java
> +        addHeaders(
тут кажется все умещается, не надо переносить

2024-05-08 14:48 UTC, Diinal commented on src/test/java/client/HttpClient.java
> +        System.out.println(request);
используй отдельный класс для логирования, нужно чтобы все это прикреплялось к отчету, пример:
https://git.moscow.alfaintra.net/projects/AUTOTEST/repos/risk_wsrm_autotest_java/browse/src/test/java/ru/alfabank/risk/wsrm/at/report/Log.java
https://git.moscow.alfaintra.net/projects/AUTOTEST/repos/risk_wsrm_autotest_java/browse/src/test/java/ru/alfabank/risk/wsrm/at/steps/XsdSteps.java#38

2024-05-08 14:48 UTC, Diinal commented on src/test/java/client/HttpClient.java
> +            responseBody = EntityUtils.toString(
в одну строку

2024-05-08 14:48 UTC, Diinal commented on src/test/java/client/HttpClient.java
> +    public String sendGetRequest(
лучше наверное будет возвращать HttpEntity, чтобы в других шагах была возможность проверки не только тела ответа. Мапу в Memory можно сделать <String, Object> - тогда любые типы можно хранить и кастовать через отдельные методы

2024-05-08 14:48 UTC, Diinal commented on src/test/java/stephelper/Memory.java
> +    public static void put(
слишком много переносов)
Они нужны только когда строка куда уходит за черту

2024-05-08 14:48 UTC, Diinal commented on src/test/java/stephelper/Memory.java
> +
лишнее

2024-05-08 14:48 UTC, Diinal commented on src/test/java/stephelper/Memory.java
> +    public static String get(
тоже избыточный перенос

2024-05-08 14:48 UTC, Diinal commented on src/test/java/client/HttpClient.java
> +            Map<String, String> headers,
хэдеры точно разные будут? может захардкодить?

2024-05-08 14:48 UTC, Diinal commented on src/test/java/client/HttpClient.java
> +            e.printStackTrace();
HttpClientException

2024-05-14 07:35 UTC, DariaBoreysha commented on build.gradle
> +task cucumber() {
Исправила

2024-05-14 07:36 UTC, DariaBoreysha commented on src/test/resources/features/SWAGGER(FindByStatus).feature
> +    When формируем GET запрос с валидным параметром "status" со значением "<status>", отправляем на "https://petstore.swagger.io/v2/pet/findByStatus" и сохраняем ответ как "response_body"
Поправила описание
Здесь валидный параметр - один из тех трех, что представлены в Examples (available, pending,sold)

2024-05-14 07:37 UTC, DariaBoreysha commented on src/test/java/client/HttpClient.java
> +        assertAnswerStatusIsOk(response
Исправила

2024-05-14 07:37 UTC, DariaBoreysha commented on src/test/java/client/HttpClient.java
> +            Map<String, String> headers,
Исправила

2024-05-14 15:33 UTC, Diinal requested changes

2024-05-14 15:33 UTC, Diinal commented on build.gradle
> +task cucumber() {
Уже лучше, но нужен отдельный параметр.
https://git.moscow.alfaintra.net/projects/AUTOTEST/repos/risk_wsrm_autotest_java/browse/build.gradle#73

2024-05-14 15:33 UTC, Diinal commented on src/test/resources/features/SWAGGER(FindByStatus).feature
> +    When формируем GET запрос с валидным параметром "status" со значением "<status>", отправляем на "https://petstore.swagger.io/v2/pet/findByStatus" и сохраняем ответ как "response_body"
Хорошо, но лучше использовать не только валидный ответ с точки зрения техник тест дизайна.
Например так:
```gherkin
Scenario Outline: Передача одного значения параметра status
    When формируем GET запрос с параметром "status" со значением "<status>", отправляем на "https://petstore.swagger.io/v2/pet/findByStatus" и сохраняем ответ в Memory как "response_body"

Examples:
      | status    | code |
      | available | 200  |
      | pending   | 200  | 
      | sold      | 200  |
      | failme    | 400  |
 ```
 
 Ожидаемый статус код пригодится потом в следующем шаге

2024-05-14 15:33 UTC, Diinal commented on src/test/java/client/HttpClient.java
> +            HttpGet request
лишние переносы
плюс лучше переименовать в addDefaultHeaders, потому что значения хедеров ты не передаешь в метод

2024-05-14 15:33 UTC, Diinal commented on src/test/java/client/HttpClient.java
> +                    .getURI())
перенеси на 80-ю строку иначе со скобками путаница

2024-05-14 15:33 UTC, Diinal commented on src/test/java/client/HttpClient.java
> +    private void assertAnswerStatusIsOk(int actualStatusCode, int expectedStatusCode) {
сейчас не используется и название не очень, ты не всегда будешь ОК 200 проверять

2024-05-14 18:02 UTC, DariaBoreysha commented on build.gradle
> +task cucumber() {
Поправила)
Не подумала, что теги лучше прописывать конкретно при запуске, а не менять каждый раз этот файл

2024-05-14 18:28 UTC, DariaBoreysha commented on src/test/java/client/HttpClient.java
> +            HttpGet request
Поправила
По поводу feature файла выше: я негативные кейсы и кейсы, где используется несколько query параметров в GET запросе, вынесла в отдельные сценарии, т.к. у них другая логика проверки получается и их не получится в рамках этого сценария проверить
В негативном сценарии другое тело ответа возвращается
А в позитивном с большим количеством параметров надо тело ответа по каждому параметру проверять отдельно

2024-05-15 12:09 UTC, Diinal approved these changes

2024-05-15 12:12 UTC, merged