New feature
DariaBoreysha/swagger_petstore_autotest pull request #17
Opened 2024-07-23 05:43 UTC by DariaBoreysha

2024-07-23 06:08 UTC, softester-git approved these changes

2024-07-23 14:24 UTC, Diinal requested changes

2024-07-23 14:24 UTC, Diinal commented on src/test/resources/features/SWAGGER(MakeOrderForPet).feature
> +    And формируем JSON на основе шаблона "makeOrderForPet.json" и сохраняем в Memory как "request_body"
может стоит в какой-либо один параметр поставить конкретное значение для второго запроса?
И затем проверять что этот параметр поменял значение
Там же данные обновиться должны
либо сохранять два ответа в разные переменные и сравнивать их, что они не равны, либо равны если апдейта нет

2024-07-24 05:47 UTC, DariaBoreysha commented on src/test/resources/features/SWAGGER(MakeOrderForPet).feature
> +    And формируем JSON на основе шаблона "makeOrderForPet.json" и сохраняем в Memory как "request_body"
Там по сути идет сравнение  ответа из GET запроса по этому id со вторым запросом, если они совпадают, то получается, что запись обновилась, если не равны, значит, запись осталась как прежде
Но я там boolean параметр complete с true на false заменила

2024-07-24 12:37 UTC, Diinal approved these changes

2024-07-24 15:31 UTC, merged