Added new method and negative scenario
DariaBoreysha/swagger_petstore_autotest pull request #5
Opened 2024-05-20 07:21 UTC by DariaBoreysha

2024-05-20 07:54 UTC, softester-git commented on src/test/java/assertions/PetstoreAssertion.java
>  import static org.assertj.core.api.Assertions.assertThat;
Данный импорт не используется в классе

2024-05-20 07:54 UTC, softester-git commented on src/test/java/assertions/PetstoreAssertion.java
> +import static steps.BaseSteps.softly;
import **static** лучше не делать. Исторически все импорты у нас не статичные

2024-05-20 08:12 UTC, softester-git approved these changes

2024-05-20 15:14 UTC, Diinal requested changes

2024-05-20 15:14 UTC, Diinal commented on src/test/java/assertions/PetstoreAssertion.java
> +            BaseSteps.softly.assertThat(jsonBody.get(i).get(fieldName).asText())
а где softly.assertAll?
в целом не очень понял для чего выводить softly в BaseSteps.
мы должны каждый раз инициализировать объект, прописывать проверки и делать непосредственный ассерт через финальный метод

2024-05-20 15:14 UTC, Diinal commented on src/test/java/steps/CommonSteps.java
> +    @And("извлекаем тело JSON из Memory переменной : {string} и проверяем соответствие полей code, type, message значениям {int}, {string}, {string}")
сделай лучше через cucumber table + универсальный метод проверки маппинга
иначе будет миллион шагов для разного набора полей
еще не понял почему шаг в common steps, а аналогичный для поля status нет

2024-05-21 06:21 UTC, DariaBoreysha commented on src/test/java/steps/CommonSteps.java
> +    @And("извлекаем тело JSON из Memory переменной : {string} и проверяем соответствие полей code, type, message значениям {int}, {string}, {string}")
Для поля status вынесла в отдельный класс, т.к. это единственная операция из тех, которые по ипр проверяем, где в ответе возвращается массив объектов, а не 1 объект + есть query параметр, в котором может быть более 1 значения, в остальных запросах либо нет параметров, либо они Path. То есть он более специфический что ли конкретно для данного метода
И по ответу с ошибкой думала тоже объединить все эти три поля type,code,message в один шаг и убрать в CommonSteps, т.к. в сваггере для всех операций ответ сервера с ошибкой идентичный, разные только значения полей
Хотя попробую разбить сейчас шаг на 3

2024-05-22 16:20 UTC, Diinal requested changes

2024-05-22 16:20 UTC, Diinal commented on src/test/resources/features/SWAGGER(FindByStatus).feature
> +      | code    | 400            |
```gherkin
| code    | <code>            |
```

2024-05-22 16:20 UTC, Diinal commented on src/test/java/assertions/PetstoreAssertion.java
>      public static <T> void assertBodyFieldValueIsCorrect(
Зачем <T>?  сделай void, expectedValue же всегда String

2024-05-22 16:20 UTC, Diinal commented on src/test/java/assertions/PetstoreAssertion.java
> +    public static SoftAssertions softly = new SoftAssertions();
нужен конструктор, так не пойдет, ты получается все все ассерты в один объект кладешь
это конечно прокатит в рамках сценария, но лучше делать по красоте
сделай не статик методы + конструктор, чтобы softly всегда был новый

также сделай softly private и добавь паблик метод assertAll в текущем классе, который будет выполнять  softly.assertAll();
это будет корректнее с точки зрения инкапсуляции

2024-05-22 16:20 UTC, Diinal commented on src/test/java/steps/CommonSteps.java
> +        Memory.put(jsonNodeVariableName, responseJsonBody);
зачем пересохранять?

2024-05-22 16:20 UTC, Diinal commented on src/test/java/assertions/PetstoreAssertion.java
>      public static void assertBodyFieldValueIsCorrect(
лучше переименовать в  assertBodyArrayFieldValuesAreCorrect

2024-05-22 16:34 UTC, DariaBoreysha commented on src/test/java/steps/CommonSteps.java
> +        Memory.put(jsonNodeVariableName, responseJsonBody);
Ой, забыла убрать, пока местами шаги меняла и думала, в каком виде лучше ответ хранить

2024-05-22 16:52 UTC, DariaBoreysha commented on src/test/java/assertions/PetstoreAssertion.java
> +    public static SoftAssertions softly = new SoftAssertions();
А впоследствии можно будет "PetstoreAssertion assertion" вынести в BaseSteps наподобие httpClient и инициализировать в хуках, чтобы не создавать новый объект в нескольких шагах в рамках одного сценария?

2024-05-22 16:53 UTC, DariaBoreysha commented on src/test/java/assertions/PetstoreAssertion.java
>      public static <T> void assertBodyFieldValueIsCorrect(
Тоже забыла поменять, пока шаги меняла(

2024-05-23 15:03 UTC, Diinal commented on src/test/java/assertions/PetstoreAssertion.java
> +    public static SoftAssertions softly = new SoftAssertions();
Можно, но зачем?
Набор ассертов должен наполняться и выполняться в рамках одного шага.
Можно другой хук применить если ты очень хочешь)
называется он BeforeStep.

Но тут есть такой минус: если делать параллелизацию выполнения сценариев, то у тебя будут коллизии между потоками из-за общего ассерта

2024-05-23 15:07 UTC, Diinal requested changes

2024-05-23 15:07 UTC, Diinal commented on src/test/java/assertions/PetstoreAssertion.java
> +    private SoftAssertions softly = new SoftAssertions();
и снова седая ноочь

```java
private SoftAssertions softly;

public PetstoreAssertion() {
    softly = new SoftAssertions();
    }

```

2024-05-23 16:55 UTC, DariaBoreysha commented on src/test/java/assertions/PetstoreAssertion.java
> +    public static SoftAssertions softly = new SoftAssertions();
Поняла, спасибо!

2024-05-23 16:56 UTC, DariaBoreysha commented on src/test/java/assertions/PetstoreAssertion.java
> +    private SoftAssertions softly = new SoftAssertions();
Ааа, разобралась, дошло😅

2024-05-24 08:53 UTC, Diinal approved these changes

2024-05-24 09:01 UTC, merged