Added "Add new pet" scenario
DariaBoreysha/swagger_petstore_autotest pull request #6
Opened 2024-05-24 10:22 UTC by DariaBoreysha

2024-05-24 10:36 UTC, DariaBoreysha commented
Есть парочка вопросов по поводу реализации этого сценария:
1) У меня была мысль не создавать pojo классы для сравнения, а сравнивать string или jsonNode переменные запроса и ответа. Но в двух случаях не особо красиво получается:
-  в случае string нужно будет файл json из request_samples отредактировать в одну строку, т.к. почему-то с сервиса тело json приходит в строку без переносов. Но тогда сам файл-образец нечитабельным визуально будет
- в случае jsonNode проблема парсинга возникает, т.к. в теле запроса все поля воспринимаются как String, а в ответе числовые поля идут как integer либо long. Какие-то обходные пути через конвертации или условия очень объемно получится, да и искала есть ли что-то такое в добавленных зависимостях, но не нашла(
2) У меня еще была мысль повыносить в папке client отдельно классы для POST, отдельно для GET, DELETE, PUT, но тогда тоже ведь придется в BaseSteps приписывать эти переменные и инициализировать в хуках, а для каждого сценария это будет излишним? поэтому оставила их все внутри HttpClient. Ну или убрать из BaseSteps и создавать объект класса по мере необходимости, но это лишние строчки кода

2024-05-27 07:05 UTC, softester-git approved these changes

2024-05-27 16:00 UTC, Diinal requested changes

2024-05-27 16:00 UTC, Diinal commented on src/test/resources/features/SWAGGER(AddNewPet).feature
> +      | status        | available                            |
статус надо в примеры вынести, потому что их несколько (+ pending и sold)

2024-05-27 16:00 UTC, Diinal commented on src/test/resources/features/SWAGGER(AddNewPet).feature
> +    Given отправляем DELETE запрос на "https://petstore.swagger.io" эндпойнт "/v2/pet/" со значением path параметра <id>
шаг не нужен если генерируем id рандомом

2024-05-27 16:00 UTC, Diinal commented on src/test/java/utils/FileUtil.java
> +    public static String readFileToString(String filePath) {
можно просто read

2024-05-27 16:00 UTC, Diinal commented on src/test/java/steps/AddNewPetSteps.java
> +    @When("извлекаем JSON из Memory: {string}, отправляем POST запрос на {string} и сохраняем ответ в Memory как {string}")
"отправляем POST запрос c телом из Memory: {string} на {string} и сохраняем ответ в Memory как {string}"

2024-05-27 16:00 UTC, Diinal commented on src/test/java/constants/Constants.java
> +    public static final String SAMPLES_FOLDER = RESOURCES + File.separator + "request_samples" + File.separator;
request_samples -> test_data

2024-05-27 16:00 UTC, Diinal commented on src/test/java/client/HttpClient.java
> +        request.setEntity(new StringEntity(body, "UTF-8"));
тут try catch не просит?

2024-05-28 05:50 UTC, DariaBoreysha commented on src/test/java/client/HttpClient.java
> +        request.setEntity(new StringEntity(body, "UTF-8"));
Не, не просит
Я бы обработала в случае чего, но тут не выделялось никак

2024-05-29 14:49 UTC, Diinal requested changes

2024-05-29 14:49 UTC, Diinal commented on src/test/java/steps/FindPetByStatusSteps.java
> +        HttpResponse response = httpClient.getMethod().get(url, parameterName, parameterValue);
я бы предложил унифицировать метод отправки запроса чтобы не было путаницы, get это довольно распространенный метод, может лучше писать sendRequest?
актуально для всех http методов

контекст не потеряется, т.к по методу getMethod() уже понятно как отправляем

2024-05-29 14:49 UTC, Diinal commented on src/test/java/client/Delete.java
> +package client;
в пакет methods
актуально также для Get и Post

2024-05-29 14:49 UTC, Diinal commented on src/test/java/client/HttpClient.java
> +    private Delete httpDelete;
httpDelete -> methodDelete
актуально и для других параметров

2024-05-29 14:49 UTC, Diinal commented on src/test/java/client/HttpClient.java
> +    public Get getMethod() {
getMethod -> methodGet
актуально и для других методов

2024-05-29 14:49 UTC, Diinal commented on src/test/java/client/Delete.java
> +    private void logDeleteRequest(URI uri, Header[] allHeaders) {
можно просто logRequest

2024-05-29 14:49 UTC, Diinal commented on src/test/java/client/Delete.java
> +    private HttpDelete composeDeleteRequest(
можно просто composeRequest

2024-05-29 14:49 UTC, Diinal commented on src/test/java/client/Get.java
> +    private static void logGetRequest(URI uri, Header[] headers) {
можно просто logRequest

2024-05-29 14:49 UTC, Diinal commented on src/test/java/client/Get.java
> +    public HttpGet composeGetRequest(
можно просто  composeRequest

2024-05-29 15:47 UTC, Diinal requested changes

2024-05-29 15:47 UTC, Diinal commented on src/test/java/client/HttpClient.java
> +    private Delete httpDelete;
не исправлено

2024-05-29 15:53 UTC, Diinal approved these changes

2024-05-29 15:53 UTC, merged