Finished realization of "Add new pet" positive scenario
DariaBoreysha/swagger_petstore_autotest pull request #7
Opened 2024-05-30 08:20 UTC by DariaBoreysha

2024-05-30 08:23 UTC, DariaBoreysha commented
Решила переделать GET класс по типу Builder, чтобы не было 2 набора практически одинаковых методов за исключением того, что в одном случае добавляется только path параметер, а в другом query

2024-05-30 15:17 UTC, Diinal requested changes

2024-05-30 15:17 UTC, Diinal commented on src/test/resources/features/SWAGGER(AddNewPet).feature
> +    And извлекаем тело ответа и тело запроса из Memory: "request_as_jsonNode", "get_response_as_jsonNode" и проверяем, что ответ и запрос совпадают
извлекаем тело **ответа** и тело **запроса**

"**request**_as_jsonNode", "get_r**esponse**_as_jsonNode"

путаница получилась.
Предлагаю переименовать шаг в более универсальный:

```gherkin
And проверяем эквивалентность JSON файлов из Memory: 
  | expected            | reality                 |
  | request_as_jsonNode | get_response_as_jsonNode|
```

Либо так:
```gherkin
And проверяем что JsonNode из Memory: "get_response_as_jsonNode" соответствует  JsonNode из Memory: "request_as_jsonNode "
```

где request_as_jsonNode - expected, а get_response_as_jsonNode - reality

2024-05-30 15:17 UTC, Diinal commented on src/test/java/utils/StringUtil.java
> +import com.fasterxml.jackson.core.JsonProcessingException;
зачем неиспользуемые импорты?

2024-05-30 15:17 UTC, Diinal commented on src/test/java/methods/Get.java
> +        if (!(endpoint == null) && !(pathParameterValue == null)) {
почему не используешь != ?

2024-05-30 19:33 UTC, DariaBoreysha commented on src/test/java/utils/StringUtil.java
> +import com.fasterxml.jackson.core.JsonProcessingException;
Ой...вот везде кажется проверила(

2024-05-30 19:34 UTC, DariaBoreysha commented on src/test/java/methods/Get.java
> +        if (!(endpoint == null) && !(pathParameterValue == null)) {
Долго думала, как будет красивее выглядеть и остановилась на этом варианте😅

2024-05-31 08:34 UTC, Diinal commented on src/test/java/methods/Get.java
> +        if (!(endpoint == null) && !(pathParameterValue == null)) {
он менее читабельный)

2024-05-31 08:40 UTC, Diinal requested changes

2024-05-31 08:40 UTC, Diinal commented on src/test/java/steps/AddNewPetSteps.java
> +    public void toJsonNode(String actual, String expected) {
лучше везде добавлять контекст что это мемори кей:
```java
public void toJsonNode(String actualMemoryKey, String expectedMemoryKey) {...}
```

в прошлый раз пропустил, тут с неймингом не очень
все шаги с проверками должны начинаться с префиксов verify или check
текущее название говорит о том что у нас идет конвертация в JsonNode и все,а это не так

2024-05-31 08:40 UTC, Diinal commented on src/test/java/steps/AddNewPetSteps.java
>      public void formRequestBody(
composeRequestBody

2024-05-31 08:40 UTC, Diinal commented on src/test/java/steps/AddNewPetSteps.java
> +    public void responseToString(
convertResponseToJsonNode

memoryVariableAsHttpResponse -> httpResponseMemoryKey
второй параметр - аналогично

2024-05-31 08:40 UTC, Diinal commented on src/test/java/steps/AddNewPetSteps.java
> +    public void requestToJsonNode(
convertRequestToJsonNode

2024-05-31 13:45 UTC, Diinal approved these changes

2024-05-31 14:03 UTC, softester-git reviewed
В классе TestDataGenerator в кейсе генерации id питомца, есть так же запрос на удаление питомца по API.
Лучше в TestDataGenerator оставить только генерацию, всю логику по очистке перед созданием лучше вынести в блок создания питомца

2024-05-31 14:12 UTC, DariaBoreysha commented
> В классе TestDataGenerator в кейсе генерации id питомца, есть так же запрос на удаление питомца по API. Лучше в TestDataGenerator оставить только генерацию, всю логику по очистке перед созданием лучше вынести в блок создания питомца

вот тут немного проблематично получается, потому что еще есть кейс по добавлению питомца на неуникальный айди

2024-06-06 10:20 UTC, Diinal requested changes

2024-06-06 10:20 UTC, Diinal commented on src/test/resources/features/SWAGGER(AddNewPet).feature
> +      | is_memory_put   | false                    |
выглядит усложненно
не вижу проблемы в том, чтобы класть ответ в мемори но не использовать его

2024-06-06 11:01 UTC, DariaBoreysha commented on src/test/resources/features/SWAGGER(AddNewPet).feature
> +      | is_memory_put   | false                    |
А, хорошо)
Я просто думала, что будет не очень красиво создавать неиспользуемые потом объекты в памяти, поэтому наворотила обходных путей(

2024-06-07 14:34 UTC, Diinal approved these changes

2024-06-07 15:01 UTC, merged